// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BmtxzrMHr0ozDeY900vAksvIBUw01nk',
    appId: '1:941688275134:web:8705b430e64807a2059eef',
    messagingSenderId: '941688275134',
    projectId: 'smart-farmer-39b56',
    authDomain: 'smart-farmer-39b56.firebaseapp.com',
    storageBucket: 'smart-farmer-39b56.firebasestorage.app',
    measurementId: 'G-8HJ1EJRBP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQJy1jMwBxcSlS7GwqEdRWGpYFfo6ih2E',
    appId: '1:941688275134:android:901f763d9ec8b650059eef',
    messagingSenderId: '941688275134',
    projectId: 'smart-farmer-39b56',
    storageBucket: 'smart-farmer-39b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2QT5i7bWEO6LqUnaAWg7et3g8yEwx2Yk',
    appId: '1:941688275134:ios:62470add8946c571059eef',
    messagingSenderId: '941688275134',
    projectId: 'smart-farmer-39b56',
    storageBucket: 'smart-farmer-39b56.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2QT5i7bWEO6LqUnaAWg7et3g8yEwx2Yk',
    appId: '1:941688275134:ios:62470add8946c571059eef',
    messagingSenderId: '941688275134',
    projectId: 'smart-farmer-39b56',
    storageBucket: 'smart-farmer-39b56.firebasestorage.app',
    iosBundleId: 'com.example.smartFarmer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7BmtxzrMHr0ozDeY900vAksvIBUw01nk',
    appId: '1:941688275134:web:ccc0ae0d5dd1e73c059eef',
    messagingSenderId: '941688275134',
    projectId: 'smart-farmer-39b56',
    authDomain: 'smart-farmer-39b56.firebaseapp.com',
    storageBucket: 'smart-farmer-39b56.firebasestorage.app',
    measurementId: 'G-LZ2NNBXZZM',
  );
}
